default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 15 } %>
  user: <%= ENV.fetch("DATABASE_USERNAME", "postgres") %>
  password: <%= ENV.fetch("DATABASE_PASSWORD", "postgres") %>
  host: <%= ENV.fetch("DATABASE_HOST", "localhost") %>
  sslmode: <%= ENV.fetch("DATABASE_SSL_MODE", "allow") %>
  sslca: <%= ENV.fetch("DATABASE_SSL_CA", "") %>

development:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME", "syncro_challenge_development") %>

test:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME", "syncro_challenge_test") %>

staging:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME", "syncro_challenge_staging") %>

production:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME", "syncro_challenge_production") %>
